### PR TITLE
Fix: validate checksum + tests

### LINKED ISSUE #5: verify checksum of seed
make sure that we raise an error:

- when it was created by swapping two words in a valid mnemonic
- when it contains an invalid word
- when it contains an unsupported number of words

### PR DESCRIPTION
**Pull request by pacu**
fixes #5 #6

### CODE REVIEW

File: Tests/MnemonicSwiftTests.swift [hunk 1]
```diff
@@ -1,156 +1,258 @@
...
-    XCTAssertNil(Mnemonic.deterministicSeedString(from: invalidMnemonic))
-  }
+        XCTAssertThrowsError(try Mnemonic.validate(mnemonic: spanishMnemonic))
+    }
+
+    /// Test that strings of mixed case are determined to be valid.
+    func testMixedCaseValidation() {
+        let mixedCaseMnemonic = "pear PEASANT PeLiCaN pen"
+        XCTAssertThrowsError(try Mnemonic.validate(mnemonic: mixedCaseMnemonic))
+    }
```
Comment (defuse) [inline Tests/MnemonicSwiftTests.swift:137]: We should also test that it throws an exception for a seed phrase that's valid except for the only thing wrong with it is it has some uppercased character:

```
let x = "human pulse approve subway climb stairs mind gentle raccoon warfare fog roast sponsor under absorb spirit hurdle animal original honey owner upper empower describe"
let y = "Human pulse approve subway climb stairs mind gentle raccoon warfare fog roast sponsor under absorb spirit hurdle animal original honey owner upper empower describe"
XCTAssertNoThrow(try Mnemonic.validate(mnemonic: x)); // having this nearby makes it easy to look at the code and know exactly whats wrong with y
XCTAssertThrowsError(try Mnemonic.validate(mnemonic: y));
```
And also check that the high-level function fails too (just to make sure it's really calling validate):

```
XCTAssertNotNil(Mnemonic.deterministicSeedBytes(mnemonic: x));
XCTAssertNil(Mnemonic.deterministicSeedBytes(mnemonic: y));
```

And also verify the checksum catches word swaps:

```
let z = "pulse human approve subway climb stairs mind gentle raccoon warfare fog roast sponsor under absorb spirit hurdle animal original honey owner upper empower describe"
XCTAssertNil(Mnemonic.deterministicSeedBytes(mnemonic: z));
```

**Review by defuse — CHANGES_REQUESTED** [review]
Implementation looks good. I'll give it some even closer review on Monday. Requested changes:

- I made some suggestions for tests I'd like to see added.
- Whenever a function is returning something that's a cryptographic key (mnemonic, seed, etc.), instead of returning `nil` it's better to throw an exception, because then there's *no way* the caller can forget to check the return value and end up using `nil` as a key (I'm not sure if swift will auto-convert `nil` to an empty string in certain situations or not, but just in case).

File: MnemonicSwift/Mnemonic.swift [hunk 2]
```diff
@@ -93,51 +134,94 @@ public enum Mnemonic {
...
+                throw MnemonicError.invalidWord(word: word)
             }
-            return true
+
+            let binaryString = String(indexInVocabulary, radix: 2).pad(toSize: 11)
+
+            seedBits.append(contentsOf: binaryString)
+        }
+
+        let checksumLength = mnemonicComponents.count / 3
```
Comment (defuse) [inline MnemonicSwift/Mnemonic.swift:190]: We should check that `mnemonicComponents.count` is valid according to the enum options in `WordCount`. I think this will accept any one-word or two-word "mnemonmic" as valid, because `2 / 3 = 0` and so it will try to check a 0-length checksum which will always pass.

Add a test for this, e.g. "flash tobacco". Currently, I think that will pass validation when it shouldn't.

File: Tests/MnemonicSwiftTests.swift [hunk 3]
```diff
@@ -1,156 +1,284 @@
...
+
+        XCTAssertNoThrow(try Mnemonic.generateMnemonic(strength: 128))
+
+        XCTAssertNoThrow(try Mnemonic.generateMnemonic(strength: 160))
+
+        XCTAssertNoThrow(try Mnemonic.generateMnemonic(strength: 192))
+
+        XCTAssertNoThrow(try Mnemonic.generateMnemonic(strength: 224))
+
+        XCTAssertNoThrow(try Mnemonic.generateMnemonic(strength: 256))
```
Comment (defuse) [inline Tests/MnemonicSwiftTests.swift:99]: Here we should compare that the outputs are actually the correct number of words, i.e. split on " " and make sure the resulting count correctly matches what's expected for the strength.

File: Tests/MnemonicSwiftTests.swift [hunk 4]
```diff
@@ -1,156 +1,284 @@
...
+        XCTAssertThrowsError(try Mnemonic.deterministicSeedBytes(from: y))
+
+    }
+
+    func testSwapTwoWords() {
+        let phrase = "human pulse approve subway climb stairs mind gentle raccoon warfare fog roast sponsor under absorb spirit hurdle animal original honey owner upper empower describe"
+        var x = phrase.components(separatedBy: " ")
+        let i = Int.random(in: 0 ..< x.count)
+        let j = Int.random(in: 0 ..< x.count)
+        x.swapAt(i, j)
```
Comment (defuse) [inline Tests/MnemonicSwiftTests.swift:223]: This test will fail even though nothing is wrong if `i` and `j` are the same.

Fix by changing to:

```
let i = Int.random(in: 1 ..< x.count)
let j = Int.random(in: 0 ..< j)
```

File: Tests/MnemonicSwiftTests.swift [hunk 5]
```diff
@@ -1,156 +1,284 @@
...
+        XCTAssertEqual("10".pad(toSize: 8), "00000010")
+        XCTAssertEqual("10".pad(toSize: 8), "00000010")
+
+        // it should not pad when size of the given string is same as target size
+        XCTAssertEqual("00000010".pad(toSize: 8), "00000010")
+
+        // it should n ot pad whe size of the given string is greater that target size
+        XCTAssertEqual("100000010".pad(toSize: 8), "100000010")
+    }
+
```
Comment (defuse) [inline Tests/MnemonicSwiftTests.swift:283]: All of the above tests are awesome! Great work!

**Review by defuse — CHANGES_REQUESTED** [review]
There's one bug to be fixed and I made some more requests for the tests. Sorry I missed it my first review! After these changes, it's looking really good!

File: MnemonicSwift/Mnemonic.swift [hunk 6]
```diff
@@ -93,51 +134,94 @@ public enum Mnemonic {
...
+    /// Validate that the given string is a valid mnemonic phrase according to BIP-39
+    /// - Parameters:
+    ///  - mnemonic: a mnemonic phrase string
+    /// - Throws:
+    ///  - `MnemonicError.wrongWordCount` if the word count is invalid
+    ///  - `MnemonicError.invalidWord(word: word)` this phase as a word that's not represented in this library's vocabulary for the detected language.
+    ///  - `MnemonicError.unsupportedLanguage` if the given phrase language isn't supported or couldn't be infered
+    ///  - `throw MnemonicError.checksumError` if the given phrase has an invalid checksum
+    public static func validate(mnemonic: String) throws {
+        let normalizedMnemonic = mnemonic.trimmingCharacters(in: .whitespacesAndNewlines)
```
[the remark this answers is not in the document]
Comment (pacu) [reply MnemonicSwift/Mnemonic.swift:168]: good catch

File: MnemonicSwift/Mnemonic.swift [hunk 7]
```diff
@@ -17,14 +17,45 @@ public enum MnemonicLanguageType {
...
     ///   - hexString: The hex string to generate a mnemonic from.
     ///   - language: The language to use. Default is english.
-    public static func mnemonicString(from hexString: String, language: MnemonicLanguageType = .english) -> String? {
-        let seedData = hexString.mnemonicData()
+    /// - Returns: the mnemonic string or nil if input is invalid
+    /// - Throws:
+    ///   - `MnemonicError.InvalidHexString`:  when an invalid string is given
+    ///   - `MnemonicError.invalidBitString` when the resulting bitstring generates an invalid word index
+    static func mnemonicString(from hexString: String, language: MnemonicLanguageType = .english) throws -> String {
+        guard let seedData = hexString.mnemonicData() else { throw MnemonicError.invalidHexstring }
```
Comment (defuse) [inline MnemonicSwift/Mnemonic.swift:58]: Not a blocker but it would be nice to throw an exception here if `seedData` isn't 16, 20, 24, 28, or 32 bytes (corresponding to the valid word counts).

**Review by defuse — CHANGES_REQUESTED** [review]
One final change to make then this is good to go!

File: MnemonicSwift/Mnemonic.swift [hunk 8]
```diff
@@ -43,48 +74,61 @@ public enum Mnemonic {
...
-            let normalizedData = self.normalized(string: mnemonic),
-            let saltData = normalized(string: "mnemonic" + passphrase) else {
-                return nil
-        }
+    ) throws -> [UInt8] {
+        let normalizedMnemonic = mnemonic.trimmingCharacters(in: .whitespacesAndNewlines)
 
+        try self.validate(mnemonic: normalizedMnemonic)
+
+        let normalizedData = try self.normalizedString(mnemonic)
```
[the remark this answers is not in the document]
Comment (pacu) [reply MnemonicSwift/Mnemonic.swift:122]: great catch

File: MnemonicSwift/Mnemonic.swift (hunk 7 above)
Comment (pacu) [reply MnemonicSwift/Mnemonic.swift:58]: you are right, also kind of completes BIP-39 specs definition into the code base

**Review by defuse — APPROVED** [review]
ACK
